/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Listar usuarios (solo ADMIN)
         * @description Ordenado por fecha de creacion descendente. El rol se lee del access token, asi que un cambio de rol requiere volver a autenticarse.
         */
        get: operations["UsersController_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Crear una cuenta
         * @description Toda cuenta nueva nace con rol USER; enviar `role` en el cuerpo no tiene efecto (regla 5).
         */
        post: operations["AuthController_register"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Autenticarse y obtener el access token
         * @description El refresh token se entrega en una cookie HttpOnly y no aparece en el cuerpo (regla 22). Credenciales invalidas devuelven siempre el mismo 401, sin distinguir si el email existe (regla 8).
         */
        post: operations["AuthController_login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Rotar el refresh token y renovar el access token
         * @description No lleva cuerpo: el token se lee de la cookie. Cada uso invalida el token presentado y emite uno nuevo (regla 13). Presentar un token ya rotado revoca la familia completa (regla 14).
         */
        post: operations["AuthController_refresh"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Cerrar sesion
         * @description Idempotente: repetirlo con un token ya revocado, o sin cookie, tambien devuelve 204, y no dispara la deteccion de reuso (regla 16).
         */
        post: operations["AuthController_logoutSession"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Perfil del usuario autenticado */
        get: operations["AuthController_me"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @enum {string} */
        Role: "USER" | "ADMIN";
        UserResponse: {
            /**
             * Format: uuid
             * @example 6f1c8b2e-3d4a-4f5b-9c8d-1e2f3a4b5c6d
             */
            id: string;
            /**
             * Format: email
             * @example ana@example.com
             */
            email: string;
            /** @example USER */
            role: components["schemas"]["Role"];
            /**
             * Format: date-time
             * @example 2026-08-05T10:00:00.000Z
             */
            createdAt: string;
        };
        PageMetaResponse: {
            /**
             * @description Total de usuarios, no de esta pagina
             * @example 42
             */
            total: number;
            /** @example 1 */
            page: number;
            /** @example 20 */
            limit: number;
            /**
             * @description Cero si no hay usuarios
             * @example 3
             */
            totalPages: number;
        };
        ListUsersResponse: {
            data: components["schemas"]["UserResponse"][];
            meta: components["schemas"]["PageMetaResponse"];
        };
        ErrorResponse: {
            /** @example 409 */
            statusCode: number;
            /** @example Conflict */
            error: string;
            /**
             * @description Texto unico, o un arreglo con un mensaje por campo cuando falla la validacion
             * @example El email ya esta registrado
             */
            message: string | string[];
            /**
             * Format: date-time
             * @example 2026-08-05T10:00:00.000Z
             */
            timestamp: string;
            /** @example /auth/register */
            path: string;
        };
        RegisterUserDto: {
            /**
             * @description Se normaliza a minusculas y sin espacios antes de validarse (regla 1)
             * @example ana@example.com
             */
            email: string;
            /**
             * @description Entre 8 y 128 caracteres (regla 4)
             * @example unaClaveSegura1
             */
            password: string;
        };
        LoginUserDto: {
            /** @example ana@example.com */
            email: string;
            /** @example unaClaveSegura1 */
            password: string;
        };
        TokenPairResponse: {
            /**
             * @description JWT firmado con HS256 (regla 9). El cliente lo mantiene en memoria.
             * @example eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI...
             */
            accessToken: string;
            /** @example Bearer */
            tokenType: string;
            /**
             * @description Vida del access token en segundos
             * @example 900
             */
            expiresIn: number;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    UsersController_list: {
        parameters: {
            query?: {
                page?: number;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Pagina de usuarios */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ListUsersResponse"];
                };
            };
            /** @description page o limit fuera de rango */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Token ausente o invalido */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Autenticado pero sin rol ADMIN */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    AuthController_register: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RegisterUserDto"];
            };
        };
        responses: {
            /** @description Cuenta creada */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserResponse"];
                };
            };
            /** @description Email o password invalidos */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description El email ya esta registrado */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    AuthController_login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginUserDto"];
            };
        };
        responses: {
            /** @description Autenticado */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenPairResponse"];
                };
            };
            /** @description Credenciales invalidas */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    AuthController_refresh: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Par renovado */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenPairResponse"];
                };
            };
            /** @description Cookie ausente, vencida, revocada o reusada */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    AuthController_logoutSession: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Sesion cerrada */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AuthController_me: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Perfil */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserResponse"];
                };
            };
            /** @description Token ausente, vencido o mal firmado */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
}
